name: itmo-FP-work
version: 0.1.0.0
github: "geny200/itmo-FP-work"
license: BSD3
author: "geny200"
copyright: "2021 geny200"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/geny200/itmo-FP-work#readme>

dependencies:
  - base >= 4.7 && < 5
  - split
  - transformers
  - directory
  - system-filepath
  - lens
  - time
  - mtl
  - deepseq
  - text
  - microlens
  - monad-par
  - random
  - filepath
  - comonad
  - vector
  - hashable
  - stm

library:
  source-dirs: src

executables:
  itmo-FP-work-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - itmo-FP-work

tests:
  itmo-FP-work-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - itmo-FP-work
      - HUnit
      - split
      - QuickCheck
      - hspec
      - async

benchmarks:
  itmo-FP-work-bench:
    main: BenchMain.hs
    source-dirs: bench
    ghc-options:
      - -eventlog
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N6
    dependencies:
      - itmo-FP-work
      - criterion
      - async